//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input/SliderInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SliderInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SliderInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SliderInputActions"",
    ""maps"": [
        {
            ""name"": ""ProgressBar"",
            ""id"": ""979e61a6-035a-498f-b13e-0fa820154b5c"",
            ""actions"": [
                {
                    ""name"": ""Fill"",
                    ""type"": ""Button"",
                    ""id"": ""22797d4c-3ac9-4e7a-bf93-600f715b378b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""405f59cc-1acb-4270-9106-f58da42f7d82"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ProgressBar
        m_ProgressBar = asset.FindActionMap("ProgressBar", throwIfNotFound: true);
        m_ProgressBar_Fill = m_ProgressBar.FindAction("Fill", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ProgressBar
    private readonly InputActionMap m_ProgressBar;
    private List<IProgressBarActions> m_ProgressBarActionsCallbackInterfaces = new List<IProgressBarActions>();
    private readonly InputAction m_ProgressBar_Fill;
    public struct ProgressBarActions
    {
        private @SliderInputActions m_Wrapper;
        public ProgressBarActions(@SliderInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fill => m_Wrapper.m_ProgressBar_Fill;
        public InputActionMap Get() { return m_Wrapper.m_ProgressBar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ProgressBarActions set) { return set.Get(); }
        public void AddCallbacks(IProgressBarActions instance)
        {
            if (instance == null || m_Wrapper.m_ProgressBarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ProgressBarActionsCallbackInterfaces.Add(instance);
            @Fill.started += instance.OnFill;
            @Fill.performed += instance.OnFill;
            @Fill.canceled += instance.OnFill;
        }

        private void UnregisterCallbacks(IProgressBarActions instance)
        {
            @Fill.started -= instance.OnFill;
            @Fill.performed -= instance.OnFill;
            @Fill.canceled -= instance.OnFill;
        }

        public void RemoveCallbacks(IProgressBarActions instance)
        {
            if (m_Wrapper.m_ProgressBarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IProgressBarActions instance)
        {
            foreach (var item in m_Wrapper.m_ProgressBarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ProgressBarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ProgressBarActions @ProgressBar => new ProgressBarActions(this);
    public interface IProgressBarActions
    {
        void OnFill(InputAction.CallbackContext context);
    }
}
